// {
//   icon: "🏠",
//   title: "Housing",
//   desc: "Rent",
//   price: 30000,
//   percent: 30,
// },

// male, single, public transport
export const option1 = [
  {
    icon: "🏠",
    title: "Housing",
    desc: "Maintenance/Repairs",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💶",
    title: "Bills",
    desc: "Utilities (Electricity, Water, Gas)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📞",
    title: "Internet and Cable",
    desc: "Airtime and Data",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😋",
    title: "Food",
    desc: "Groceries, Dinning out",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🚌",
    title: "Transportation",
    desc: "Ride-Sharing Services (Uber, Bolt)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "❤️‍🩹",
    title: "Health and Fitness",
    desc: "Haircuts/Barber, Skincare and Grooming Products",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👲",
    title: "Personal Care",
    desc: "Personal care",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🎧",
    title: "Entertainment",
    desc: "Streaming Services (Netflix, Spotify) etc",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🤑",
    title: "Savings",
    desc: "Emergency Fund, retirement savings",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📊",
    title: "Investment",
    desc: "Investments (Stocks, Bonds, Mutual Funds)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💳 ",
    title: "Debt Repayment",
    desc: "Loan app & Personal loans",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🛍️",
    title: "Clothing",
    desc: "Clothes, shoes & wrist watch",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👩‍💻",
    title: "Self-Development",
    desc: "Online Courses, workshop seminars",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😶",
    title: "Miscellaneous",
    desc: "Gifts, Donations/Charity",
    price: 30000,
    percent: 30,
  },
  {
    icon: "✈️",
    title: "Travel",
    desc: "Weekend Trips, family visit",
    price: 30000,
    percent: 30,
  },
];

// male, single, private car
export const option2 = [
  {
    icon: "🏠",
    title: "Housing",
    desc: "Maintenance/Repairs",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💶",
    title: "Bills",
    desc: "Utilities (Electricity, Water, Gas)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📞",
    title: "Internet and Cable",
    desc: "Airtime and Data",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😋",
    title: "Food",
    desc: "Groceries, Dinning out",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🚌",
    title: "Transportation",
    desc: "Maintenance and repairs, fuel",
    price: 30000,
    percent: 30,
  },
  {
    icon: "❤️‍🩹",
    title: "Health and Fitness",
    desc: "Haircuts/Barber, Skincare and Grooming Products",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👲",
    title: "Personal Care",
    desc: "Personal care",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🎧",
    title: "Entertainment",
    desc: "Streaming Services (Netflix, Spotify) etc",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🤑",
    title: "Savings",
    desc: "Emergency Fund, retirement savings",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📊",
    title: "Investment",
    desc: "Investments (Stocks, Bonds, Mutual Funds)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💳 ",
    title: "Debt Repayment",
    desc: "Loan app & Personal loans",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🛍️",
    title: "Clothing",
    desc: "Clothes, shoes & wrist watch",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👩‍💻",
    title: "Self-Development",
    desc: "Online Courses, workshop seminars",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😶",
    title: "Miscellaneous",
    desc: "Gifts, Donations/Charity",
    price: 30000,
    percent: 30,
  },
  {
    icon: "✈️",
    title: "Travel",
    desc: "Weekend Trips, family visit",
    price: 30000,
    percent: 30,
  },
];

// male, married, public transport
export const option3 = [
  {
    icon: "🏠",
    title: "Housing",
    desc: "Maintenance/Repairs",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💶",
    title: "Bills",
    desc: "Utilities (Electricity, Water, Gas)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📞",
    title: "Internet and Cable",
    desc: "Airtime and Data",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😋",
    title: "Food",
    desc: "Groceries, Dinning out",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🚌",
    title: "Transportation",
    desc: "Ride-Sharing Services (Uber, Bolt)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "❤️‍🩹",
    title: "Health and Fitness",
    desc: "Haircuts/Barber, Skincare and Grooming Products",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👲",
    title: "Personal Care",
    desc: "Personal care",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🎧",
    title: "Entertainment",
    desc: "Streaming Services (Netflix, Spotify) etc",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🤑",
    title: "Savings",
    desc: "Emergency Fund, retirement savings",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📊",
    title: "Investment",
    desc: "Investments (Stocks, Bonds, Mutual Funds)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💳 ",
    title: "Debt Repayment",
    desc: "Loan app & Personal loans",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🛍️",
    title: "Clothing",
    desc: "Clothes, shoes & wrist watch",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👩‍💻",
    title: "Self-Development",
    desc: "Online Courses, workshop seminars",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😶",
    title: "Miscellaneous",
    desc: "Gifts, Donations/Charity",
    price: 30000,
    percent: 30,
  },
  {
    icon: "✈️",
    title: "Travel",
    desc: "Weekend Trips, family visit",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👶️",
    title: "Children",
    desc: "Childcare/School Fees",
    price: 30000,
    percent: 30,
  },
];

// male, married, private car
export const option4 = [
  {
    icon: "🏠",
    title: "Housing",
    desc: "Maintenance/Repairs",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💶",
    title: "Bills",
    desc: "Utilities (Electricity, Water, Gas)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📞",
    title: "Internet and Cable",
    desc: "Airtime and Data",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😋",
    title: "Food",
    desc: "Groceries, Dinning out",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🚌",
    title: "Transportation",
    desc: "Maintenance and repairs, fuel",
    price: 30000,
    percent: 30,
  },
  {
    icon: "❤️‍🩹",
    title: "Health and Fitness",
    desc: "Haircuts/Barber, Skincare and Grooming Products",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👲",
    title: "Personal Care",
    desc: "Personal care",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🎧",
    title: "Entertainment",
    desc: "Streaming Services (Netflix, Spotify) etc",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🤑",
    title: "Savings",
    desc: "Emergency Fund, retirement savings",
    price: 30000,
    percent: 30,
  },
  {
    icon: "📊",
    title: "Investment",
    desc: "Investments (Stocks, Bonds, Mutual Funds)",
    price: 30000,
    percent: 30,
  },
  {
    icon: "💳 ",
    title: "Debt Repayment",
    desc: "Loan app & Personal loans",
    price: 30000,
    percent: 30,
  },
  {
    icon: "🛍️",
    title: "Clothing",
    desc: "Clothes, shoes & wrist watch",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👩‍💻",
    title: "Self-Development",
    desc: "Online Courses, workshop seminars",
    price: 30000,
    percent: 30,
  },
  {
    icon: "😶",
    title: "Miscellaneous",
    desc: "Gifts, Donations/Charity",
    price: 30000,
    percent: 30,
  },
  {
    icon: "✈️",
    title: "Travel",
    desc: "Weekend Trips, family visit",
    price: 30000,
    percent: 30,
  },
  {
    icon: "👶️",
    title: "Children",
    desc: "Childcare/School Fees",
    price: 30000,
    percent: 30,
  },
];

export const expensesInOther = [
  "5",
  "10",
  "20",
  "30",
  "50",
  "70",
  "80",
  "100",
  "200",
  "300",
  "400",
  "500",
  "700",
  "800",
  "1000",
  "2000",
];

export const expensesInNaira = [
  "1000",
  "2000",
  "3000",
  "4000",
  "5000",
  "6000",
  "7000",
  "8000",
  "9000",
  "10000",
  "20000",
  "25000",
  "30000",
  "50000",
  "100000",
  "300000",
  "500000",
];
